name: Create Release Branch
on:
    workflow_dispatch:
        inputs:
            prefix:
                description: "Type (release | hotfix)"
                default: release
                required: true
jobs:
    branching:
        if: github.event.inputs.prefix == 'release' || github.event.inputs.prefix == 'hotfix'
        runs-on: ubuntu-latest
        name: Create Branch
        steps:
            - name: Checkout alpha to create RELEASE
              uses: actions/checkout@v2
              if: github.event.inputs.prefix == 'release'
              with:
                ref: "alpha"

            - name: Checkout master to create HOTFIX
              uses: actions/checkout@v2
              if: github.event.inputs.prefix == 'hotfix'
              with:
                ref: "master"

            - name: Install Node
              uses: actions/setup-node@v1
              with:
                  node-version: "10.17.0"

            - name: Create new branch
              run: |
                git config --global user.name 'Github Robot'
                git config --global user.email '<>'
                git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
            
            - name: Increase version minor
              if: github.event.inputs.prefix == 'release'
              run: |
                npm --no-git-tag-version version minor
                APP_VERSION=$(node -p "require('./package').version")
                echo "app_version=$APP_VERSION" >> $GITHUB_ENV

            - name: Increase version patch
              if: github.event.inputs.prefix == 'hotfix'
              run: |
                npm --no-git-tag-version version patch
                APP_VERSION=$(node -p "require('./package').version")
                echo "app_version=$APP_VERSION" >> $GITHUB_ENV
            
            - name: Push to origin
              run: |
                git checkout -b release/v${{ env.app_version }}
                git add .
                git commit -m "Bumped App Version to ${{ env.app_version }}"
                git push --set-upstream origin release/v${{ env.app_version }}

            - name: Checkout develop to update release notes
              uses: actions/checkout@v2
              with:
                ref: "develop"

            - name: Update readme file
              run: |
                sed -i --regexp-extended 's/\*\*release\/\S+\*\*/**release\/v${{ env.app_version }}**/' readme.md
                sed -i --regexp-extended 's/created at \*.+\*/created at *'"$(TZ=Europe/Berlin date)"'*/' readme.md
                git add .
                git commit -m "Updated readme.md for release/v${{ env.app_version }}"
                git push