name: Tag Release Version On Master
on:
  push:
    branches: [master]

jobs:
  tagging:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Node
        uses: actions/setup-node@v1
        with:
            node-version: "10.17.0"

      - name: Create and push tag
        run: |
          git config --global user.name 'Github Robot'
          git config --global user.email '<>'
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY

          APP_VERSION=$(node -p "require('./package').version")
          git tag -a v$APP_VERSION -m "bcc version $APP_VERSION"
          git push origin --tags